//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQDEF.Tests {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AQDEF_Samples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AQDEF_Samples() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AQDEF.Tests.AQDEF.Samples", typeof(AQDEF_Samples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2001/2 characteristic2
        ///		1 0 01.01.2014/00:00:00        2 0 01.01.2014/00:00:00       
        ///		3 0 01.01.2014/00:00:00        4 0 01.01.2014/00:00:00       
        ///		K0014/1/0 partId1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithAdditionalDataForAllValuesOfSingleCharacteristic {
            get {
                return ResourceManager.GetString("dfqWithAdditionalDataForAllValuesOfSingleCharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		1 0 01.01.2014/00:00:00        
        ///		2 0 01.01.2014/00:00:00        
        ///		K0014/1 partId2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithAdditionalDataForLastValue {
            get {
                return ResourceManager.GetString("dfqWithAdditionalDataForLastValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		1 0 01.01.2014/00:00:00        
        ///		2 0 01.01.2014/00:00:00        
        ///		K0014/1/1 partId1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithAdditionalDataForValueWithIndex {
            get {
                return ResourceManager.GetString("dfqWithAdditionalDataForValueWithIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2001/2 characteristic2
        ///		1 0 01.01.2014/00:00:00        2 0 01.01.2014/00:00:00       
        ///		3 0 01.01.2014/00:00:00        4 0 01.01.2014/00:00:00       
        ///		K0014/0/1 partId1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithAdditionalDataForValueWithIndexAndAllCharacteristics {
            get {
                return ResourceManager.GetString("dfqWithAdditionalDataForValueWithIndexAndAllCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2004/1 0
        ///		K2001/2 characteristic2
        ///		K2004/2 1
        ///		1 0 01.01.2014/00:00:00        1000 0 0 0 01.01.2014/00:00:00        
        ///		1.1 0 01.01.2014/00:00:00        1000 1 0 0 01.01.2014/00:00:00        
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithAttributeCharacteristicWithBinaryValues {
            get {
                return ResourceManager.GetString("dfqWithAttributeCharacteristicWithBinaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001/1 part
        ///		K2001/1 characteristic
        ///		K0001/1 1
        ///		K0004/1 1.1.2014/10:30:59
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithDate {
            get {
                return ResourceManager.GetString("dfqWithDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001/1 part
        ///		K1002
        ///		K1003/1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithEmptyKeys {
            get {
                return ResourceManager.GetString("dfqWithEmptyKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part
        ///		K2001/1 characteristic 1
        ///		K2030/1 0
        ///		K2031/1 0
        ///		K2001/2 characteristic 2
        ///		K2030/2 0
        ///		K2031/2 0
        ///		K5111/1 1
        ///		K5112/2 1
        ///		K5112/3 2
        ///		K5102/1 1
        ///		K5102/1 2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithEmptySimpleAndNormalHierarchy {
            get {
                return ResourceManager.GetString("dfqWithEmptySimpleAndNormalHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		1 0 01.01.2014/00:00:00        
        ///		K0014/1/ partId1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithEmptyValueIndex {
            get {
                return ResourceManager.GetString("dfqWithEmptyValueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part
        ///		K2001/1 characteristic 1
        ///		K2001/2 characteristic 2
        ///		K2001/3 characteristic 3
        ///		K2001/4 characteristic 4
        ///		K2001/5 characteristic 5
        ///		K2001/6 characteristic 6
        ///		K5001/1 group 1
        ///		K5001/1 group 1
        ///		K5111/1 1
        ///		K5112/2 1
        ///		K5112/3 2
        ///		K5112/4 3
        ///		K5112/5 4
        ///		K5112/6 5
        ///		K5112/7 6
        ///		K5113/8 1
        ///		K5102/1 1
        ///		K5103/1 3
        ///		K5102/3 3
        ///		K5102/3 4
        ///		K5103/1 8
        ///		K5102/8 5
        ///		K5102/8 6
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithHierarchy {
            get {
                return ResourceManager.GetString("dfqWithHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1010/1 1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithInteger {
            get {
                return ResourceManager.GetString("dfqWithInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1-1 characteristic1
        ///		1 0 01.01.2014/00:00:00        
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithInvalidIndex {
            get {
                return ResourceManager.GetString("dfqWithInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part
        ///		K2002/0 common title
        ///		K2001/1 characteristic1
        ///		K2001/2 characteristic2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllCharacteristics {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 4
        ///		K1001/1 part1
        ///		K2002/0 common title part1
        ///		K2001/1 part1 - characteristic1
        ///		K2001/2 part1 - characteristic2
        ///
        ///		K1001/2 part2
        ///		K2002/0 common title part2
        ///		K2001/3 part2 - characteristic1
        ///		K2001/4 part2 - characteristic2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllCharacteristicsOnMultipleParts {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllCharacteristicsOnMultipleParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 4
        ///		K1001/1 part1
        ///		K2002/0 common title
        ///		K2001/1 part1 - characteristic1
        ///		K2001/2 part1 - characteristic2
        ///
        ///		K1001/2 part2
        ///		K2001/3 part2 - characteristic1
        ///		K2001/4 part2 - characteristic2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllCharacteristicsOnOneOfMultipleParts {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllCharacteristicsOnOneOfMultipleParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1002/0 common title
        ///		K1001/1 part1
        ///		K1001/2 part2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllParts {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/0 common title
        ///		K1001/1 part
        ///		K2002/0 common title
        ///		K2001/1 characteristic
        ///		K0014/0 common identifier
        ///		K0001/1 1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllPartsCharacteristicsAndValues {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllPartsCharacteristicsAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1002/0 common title
        ///		K1001/1 part1
        ///		K1002/1 explicit title
        ///		K1001/2 part2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllPartsSomeDefinedExplicitly {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllPartsSomeDefinedExplicitly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001/1 part
        ///		K2001/1 characteristic1
        ///		K0014/0 identifier
        ///		K0001/1 1
        ///		K0001/1 2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToAllValuesBeforeValue {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToAllValuesBeforeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001/1 part
        ///		K2001/1 characteristic1
        ///		K0001/1 1
        ///		K0014/0 identifier 1
        ///		K0001/1 2
        ///		K0014/0 identifier 2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToEachValueSet {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToEachValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001/1 part
        ///		K2001/1 characteristic1
        ///		K0001/1 1
        ///		K0014/0 identifier
        ///		K0001/1 2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithKeyAppliedToSingleValueSet {
            get {
                return ResourceManager.GetString("dfqWithKeyAppliedToSingleValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2001/2 characteristic2
        ///		1 0 01.01.2014/00:00:00        2 0 01.01.2014/00:00:00        3 0 01.01.2014/00:00:00        
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithMoreValuesThanCharacteristics {
            get {
                return ResourceManager.GetString("dfqWithMoreValuesThanCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part
        ///		K2001/1 characteristic1
        ///		K2001/2 characteristic2
        ///		K0001/1 1
        ///		K0001/2 3
        ///		K0004/0 1.1.2014/10:30:59
        ///		K0010/0 153
        ///		K0014/0 common identifier
        ///		K0001/1 2
        ///		K0001/2 4
        ///		K0004/0 1.1.2014/10:31:00
        ///		K0010/0 154
        ///		K0014/0 common identifier 2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithMultipleKeysAppliedToAllValues {
            get {
                return ResourceManager.GetString("dfqWithMultipleKeysAppliedToAllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part
        ///		K2001/1 characteristic 1
        ///		K2030/1 1
        ///		K2031/1 0
        ///		K2001/2 characteristic 2
        ///		K2030/2 0
        ///		K2031/2 1
        ///		K5111/1 1
        ///		K5112/2 1
        ///		K5112/3 2
        ///		K5102/1 1
        ///		K5102/1 2
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithSimpleAndNormalHierarchy {
            get {
                return ResourceManager.GetString("dfqWithSimpleAndNormalHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001/1 part
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithString {
            get {
                return ResourceManager.GetString("dfqWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2004/0 0
        ///		1 0 01.01.2014/00:00:00        
        ///		K1001/2 part2
        ///		K2001/2 characteristic2
        ///		2 0 01.01.2014/00:00:00        
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithTwoPartsWithBinaryValuesAfterEachPart {
            get {
                return ResourceManager.GetString("dfqWithTwoPartsWithBinaryValuesAfterEachPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2004/0 0
        ///		K1001/2 part2
        ///		K2001/2 characteristic2
        ///		1 0 01.01.2014/00:00:00        2 0 01.01.2014/00:00:00        
        ///		1.1 0 01.01.2014/00:00:00        2.1 0 01.01.2014/00:00:00        
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithTwoPartsWithBinaryValuesAtTheEnd {
            get {
                return ResourceManager.GetString("dfqWithTwoPartsWithBinaryValuesAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2004/0 0
        ///		K0001/1 1
        ///		K0001/1 1.1
        ///		K1001/2 part2
        ///		K2001/2 characteristic2
        ///		K0001/2 2
        ///		K0001/2 2.1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithTwoPartsWithValuesAfterEachPart {
            get {
                return ResourceManager.GetString("dfqWithTwoPartsWithValuesAfterEachPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2004/0 0
        ///		K1001/2 part2
        ///		K2001/2 characteristic2
        ///		K0001/1 1
        ///		K0001/1 1.1
        ///		K0001/2 2
        ///		K0001/2 2.1
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithTwoPartsWithValuesAtTheEnd {
            get {
                return ResourceManager.GetString("dfqWithTwoPartsWithValuesAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 1
        ///		K1001 part
        ///		K1002 title
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithUnindexedPart {
            get {
                return ResourceManager.GetString("dfqWithUnindexedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///		K0100 2
        ///		K1001/1 part1
        ///		K2001/1 characteristic1
        ///		K2002/1/1 invalid characteristic name
        ///		1 0 01.01.2014/00:00:00        
        ///		2 0 01.01.2014/00:00:00        
        /// 的本地化字符串。
        /// </summary>
        internal static string dfqWithValueIndexPlacedOnCharacteristicKKey {
            get {
                return ResourceManager.GetString("dfqWithValueIndexPlacedOnCharacteristicKKey", resourceCulture);
            }
        }
    }
}
